; LightSense - ESP32-S3 Flicker Meter
; Board: Wifiduino32S3 (Blinker WiFiduino32S3, ESP32-S3, 8MB Flash)

[env:wifiduino32s3]
platform = espressif32
board = wifiduino32s3
framework = arduino
monitor_speed = 115200
